channels: [32, 64, 128, 256]
tensorboard_log_dir: 'runs/stylegan2_256x256_test_small'
tensorboard_image_interval: 500
checkpoint_dir: 'checkpoints/stylegan2_256x256_test_small'
checkpoint_interval: 500
data_dir: '/home/armaank/archml/data/ArtchDaily-Share-256'
gpu: [0]
